server:
  port: 8083
  tomcat:
    max-http-post-size: -1


chatgpt:
  api: "https://api.openai.com/v1/chat/completions"
#  替换成你自己的Bearer $OPENAI_API_KEY，用代码里的EncryptUtil加密
  skey: "your_key"
  model: "gpt-3.5-turbo"

