server:
  port: 8083
  tomcat:
    max-http-post-size: -1


chatgpt:
  api: "https://api.openai.com/v1/chat/completions"
  skey: "2eaQrVip0Bi0jcHxMVB6eOZI3uvfJKLCO7w6xIxdJIbBlfAdMGjni6tA1nIkmDhLq3eDkY1aJ+ntF+3yrmajgja7vKIpBOgviB4="
  model: "gpt-3.5-turbo"

